### ISSUE TITLE
What should a webdev workshop or starter course for newbies look like in 2018?

### ISSUE THREAD

**Issue by lindtdev** [rughh/planning#94]
Hey community,

I am currently teaching a Rails course for beginners for Women Techmakers. When I started learning Ruby and Rails myself, I already knew a lot of basics that I didn't have to learn first so it all seemed very smooth sailing to me. But now I'm starting to wonder if Ruby and Rails is the best route. What would you teach a newbie in 2018?

Some key struggling points:
- the setup takes ages. For beginners, setting up means not just installing Ruby and heroku-cli, but also git, an editor, setting up Github, learning how to work on the command line
- is it really such a great idea to teach ERB templates in 2018 when views are increasingly Javascript-only?
- they have to learn SOME Javascript anyway, why not start with a full-Javascript stack?
- personal opinion, and this goes against everything I said in favor of Javascript, but I'm rather in favor of starting out with a statically typed language

What do you think?

**Comment by embasbm** [comment]
Personally, I started on RoR with [Michael Hartl tutorial](https://www.railstutorial.org/). It goes through all the stack but without getting into anything deeply. It gets to the point of making an entire app running/using all these different tools.

I like the approach Michael Hartl takes about Rails and Ruby; first, a chapter for Rails, then he jumps to Ruby, and then he goes back to Rails. This way you kind of know about both of them and can differentiate between them.

About Git, Heroku, JS, ERB, testing, etc; in this tutorial, you touch all of them, slightly. Of course, there are links to each and everyone in case you want to get a better understanding.

I always recommend this tutorial since it worked for me, I had to do it twice, though, for the first time, because it was too much.

**Comment by lindtdev** [comment]
Yep, Hartl is a classic! That's the same tutorial I used back in the day. We are also using it for the workshop. But it just introduces too much in the first chapters. It's OK for people who know about git and testing. But I mean people who didn't know how to open the terminal on their Macbook. It's just too much. There should be a way to add all these setup steps and tools gradually.

**Comment by emrox** [comment]
There is the basic [Learn to program](https://pine.fm/LearnToProgram/) tutorial which goes thru the basic concepts of programming using ruby

**Comment by lindtdev** [comment]
Oh right! I think I remember that one, it was indeed very good as introduction to Ruby. I'll have a look at it again.
